#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d           

bspc config border_width         2
bspc config normal_border_color \#6272a4
bspc config active_border_color \#6272a4
bspc config focused_border_color \#6272a4
bspc config presel_feedback_color \#6272a4
bspc config window_gap          20

bspc config focus_follows_pointer true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^6'
bspc rule -a Firefox desktop='^1'

setxkbmap pl
nitrogen --restore
picom --daemon
sh $HOME/.config/polybar/launch.sh
